dictionary = {'login': 'Advik-B',
              'id': 86160411, 'node_id': 'MDQ6VXNlcjg2MTYwNDEx',
              'avatar_url': 'https://avatars.githubusercontent.com/u/86160411?v=4',
              'gravatar_id': '',
              'url': 'https://api.github.com/users/Advik-B',
              'html_url': 'https://github.com/Advik-B',
              'followers_url': 'https://api.github.com/users/Advik-B/followers',
              'following_url': 'https://api.github.com/users/Advik-B/following{/other_user}', 'gists_url': 'https://api.github.com/users/Advik-B/gists{/gist_id}',
              'starred_url': 'https://api.github.com/users/Advik-B/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Advik-B/subscriptions', 'organizations_url': 'https://api.github.com/users/Advik-B/orgs',
              'repos_url': 'https://api.github.com/users/Advik-B/repos',
              'events_url': 'https://api.github.com/users/Advik-B/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Advik-B/received_events', 'type': 'User',
              'site_admin': False, 'name': 'Advik', 'company': None,
              'blog': 'https://advik-py.blogspot.com/',
              'location': 'Asia, India, Telangana, Hyderabad, Bowenpally, sancharpuri, phase 1, plot.no 72',
              'email': None,
              'hireable': None,
              'bio': None,
              'twitter_username': None,
              'public_repos': 26,
              'public_gists': 2,
              'followers': 1,
              'following': 3,
              'created_at': '2021-06-19T15:11:42Z',
              'updated_at': '2021-11-28T09:03:52Z'}